spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    database-platform:
    open-in-view:
    hibernate:
      ddl-auto:
    properties:
        hibernate:
            format_sql: true
            show_sql: false
            jdbc:
            time_zone: UTC
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

jwt:
  secret: ${JWT_SECRET:}
